version: "3.8"

services:
  rag_quickstart:
    container_name: rag_quickstart
    image: heartexlabs/label-studio-ml-backend:llm-master
    build:
      context: .
      args:
        TEST_ENV: ${TEST_ENV}
    environment:
      - LABEL_STUDIO_URL=http://localhost:8082
      - LABEL_STUDIO_API_KEY=yourapikeyhere
      # Specify the path (within this container) to the directory with the documentation files
      - DOCUMENTATION_PATH=/path/to/your/docs
      # Specify glob pattern for documentation files (ex: **/*.md for all markdown files under DOCUMENTATION_PATH)
      - DOCUMENTATION_GLOB=**/*.md
      # Specify API key for openai
      - OPENAI_API_KEY=yourapikeyhere
      # Specify embedding model name for openai (by default it uses "text-embedding-3-small")
      - OPENAI_EMBEDDING_MODEL=text-embedding-3-small
      # Specify RAG model name for openai (by default it uses "gpt-3.5-turbo-0125")
      - OPENAI_RAG_MODEL=gpt-3.5-turbo-0125
      # Specify evaluation model name for openai (by default it uses "gpt-3.5-turbo-0125")
      - OPENAI_EVALUATION_MODEL=gpt-3.5-turbo-0125
      # Log level for the server
      - LOG_LEVEL=DEBUG
      # specify these parameters if you want to use basic auth for the model server
      - BASIC_AUTH_USER=
      - BASIC_AUTH_PASS=
      - CLEAR_ADDITIONAL_INSTRUCTIONS_BETWEEN_TASKS=0
    ports:
      - 9090:9090
    volumes:
      - "./data/server:/data"
