__include__: [
  '../../dataset/obj365_detection.yml',
  '../../runtime.yml',
  '../include/dataloader.yml',
  '../include/optimizer.yml',
  '../include/dfine_hgnetv2.yml',
]

output_dir: ./output/dfine_hgnetv2_s_obj365


DFINE:
  backbone: HGNetv2

HGNetv2:
  name: 'B0'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True

DFINETransformer:
  num_layers: 3  # 4 5 6
  eval_idx: -1  # -2 -3 -4

HybridEncoder:
  in_channels: [256, 512, 1024]
  hidden_dim: 256
  depth_mult: 0.34
  expansion: 0.5

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000125
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.000125
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.00025
  betas: [0.9, 0.999]
  weight_decay: 0.000125
#   weight_decay: 0.00005  # Faster convergence (optional)


epochs: 36 # Early stop
train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 500
  collate_fn:
    stop_epoch: 500
    base_size_repeat: 20

checkpoint_freq: 1
print_freq: 1000
