version: "3.11"

services:
  ml-backend:
    container_name: ml-backend
    build: .
    environment:
      - MODEL_DIR=/data/models
      - WORKERS=2
      - THREADS=4
      - LOG_LEVEL=DEBUG
      # Add these variables if you want to access the images stored in Label Studio
      - LABEL_STUDIO_HOST=
      - LABEL_STUDIO_ACCESS_TOKEN=
      # use these if you want to use segment anything instead of bounding box predictions from input text prompts
      - USE_MOBILE_SAM=
      - MOBILE_SAM_CHECKPOINT=
    ports:
      - "9090:9090"
    volumes:
      - "./data/ml-backend:/data"
