version: "3.8"

services:
  openai:
    container_name: openai
    build: .
    environment:
      - LABEL_STUDIO_ML_BACKEND_V2=true
      - LOG_LEVEL=DEBUG
      - OPENAI_API_KEY=<your-openai-api-key>
    ports:
      - "9090:9090"
    volumes:
      - "./prompt.txt:/app/prompt.txt"