version: "3.8"

services:
  label-studio-ml-backend:
    build: .
    container_name: ls-ml-backend
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "9090:9090"
    volumes:
      - .:/app
    command: python openai_predictor.py

  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    environment:
      - LABEL_STUDIO_ML_BACKENDS=ml_backend:9090
    ports:
      - "8080:8080"
    depends_on:
      - label-studio-ml-backend
    volumes:
      - label-studio-data:/label-studio/data
