version: "3.8"

services:
  ml-backend:
    container_name: ml-backend
    image: humansignal/ml-backend:v0
    build:
      context: .
      args:
        TEST_ENV: ${TEST_ENV:-"false"}
    environment:
      - MODEL_DIR=/data/models
      - WORKERS=1
      - THREADS=8
      - LOG_LEVEL=DEBUG
      - ANY=PARAMETER
    ports:
      - "9090:9090"
