version: "3.8"

services:
  huggingface_llm:
    container_name: huggingface_llm
    image: heartexlabs/label-studio-ml-backend:huggingfacellm-master
    init: true
    build:
      context: .
      args:
        TEST_ENV: ${TEST_ENV}
    environment:
      # specify these parameters if you want to use basic auth for the model server
      - BASIC_AUTH_USER=
      - BASIC_AUTH_PASS=
      # set the log level for the model server
      - LOG_LEVEL=DEBUG
      # specify the model name
      - MODEL_NAME=facebook/opt-125m
      # specify max generation length
      - MAX_LENGTH=50
      # specify the number of workers and threads for the model server
      - WORKERS=1
      - THREADS=8
      # specify the model directory (likely you don't need to change this)
      - MODEL_DIR=/data/models
    ports:
      - "9090:9090"
    volumes:
      - "./data/server:/data"
      - "./data/.cache:/root/.cache"
