version: "3.8"

services:
  huggingface:
    container_name: huggingface
    image: humansignal/huggingface-gpt:v0
    build: .
    environment:
      - MODEL_DIR=/data/models
      - TRANSFORMERS_CACHE=/data/models/transformers-cache
      - MODEL_NAME=microsoft/DialoGPT-small
      - LOG_LEVEL=DEBUG
    ports:
      - 9091:9090
    volumes:
      - "./data/server:/data"