version: "3.8"

services:
  mmdetection-3:
    container_name: mmdetection-3
    build: .
    environment:
      - MODEL_DIR=/data/models
    ports:
      - 9090:9090
    volumes:
      - "./data/server:/data"
      - "./logs:/tmp"